### PR TITLE
 Betterdiscord Full Implementation

### PR DESCRIPTION
**Pull request by JustOptimize**
With 9894fab i added all common functions and commented non common ones (only for betterdiscord)

### CODE REVIEW

**Comment by JustOptimize** [comment]
Betterdiscord Webpack & Data implemented

**Review by Davilarek — COMMENTED** [review]
The reason it was (and I think it should be) an `interface` is that so every other client mod implementation class needs to implement **each** of the methods, and now with usage of `extends` it's not needed as opposed to `implements`

**Comment by JustOptimize** [comment]
> The reason it was (and I think it should be) an `interface` is that so every other client mod implementation class needs to implement **each** of the methods, and now with usage of `extends` it's not needed as opposed to `implements`

Switched to implements with last commit

**Comment by JustOptimize** [comment]
> also I'm currently working on adding custom implementation code to the output for client mods that don't support a specific functionality

There shouldn't be specific functionality in the end, custom functionality exists only until replugged gets fully implemented

**Comment by Davilarek** [comment]
> > also I'm currently working on adding custom implementation code to the output for client mods that don't support a specific functionality
> 
> There shouldn't be specific functionality in the end, custom functionality exists only until replugged gets fully implemented

when I finish the basics I will push onto a different branch and you'll see what I mean

**Comment by JustOptimize** [comment]
> when I finish the basics I will push onto a different branch and you'll see what I mean

You should be committing already to a "Draft" branch while working on it even if it doen't work so you can keep track of your progress and track bugs

**Comment by Davilarek** [comment]
> > when I finish the basics I will push onto a different branch and you'll see what I mean
> 
> You should be committing already to a "Draft" branch while working on it even if it doen't work so you can keep track of your progress and track bugs

it doesn't even compile currently lol

**Comment by JustOptimize** [comment]
> it doesn't even compile currently lol

yeah but it's still progress

**Comment by Davilarek** [comment]
then take a look at #8

**Comment by Davilarek** [comment]
Now after merging of #8 I guess this PR needs to be redone

**Comment by Davilarek** [comment]
😕

**Comment by JustOptimize** [comment]
> 😕

Dealing with the merge is not worth it especially for no actual features except bdapi "implementation".

**Pull request closed without merging**
